/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ultimate_tic_tac_toe;

/**
 *
 * @author gaudium
 */
import javax.swing.JFrame;
import user.*;

public class UltimateComputerSelectFrame extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public UltimateComputerSelectFrame() {
        setSize(938, 788);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // this method display the JFrame to center position of a screen
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnGoToGame = new javax.swing.JButton();
        cmbXOrO = new javax.swing.JComboBox<>();
        cmbDifficulty = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(938, 788));
        getContentPane().setLayout(null);

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("X or O?:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(250, 420, 110, 33);

        lblUsername.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Difficulty:");
        getContentPane().add(lblUsername);
        lblUsername.setBounds(250, 340, 110, 33);

        lblTitle.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SELECT COMPUTER OPTIONS");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(0, 230, 940, 50);

        btnGoToGame.setBackground(new java.awt.Color(0, 102, 255));
        btnGoToGame.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnGoToGame.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToGame.setText("Go to Game");
        btnGoToGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoToGame);
        btnGoToGame.setBounds(250, 520, 430, 40);

        cmbXOrO.setBackground(new java.awt.Color(0, 102, 255));
        cmbXOrO.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        cmbXOrO.setForeground(new java.awt.Color(255, 255, 255));
        cmbXOrO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "O" }));
        getContentPane().add(cmbXOrO);
        cmbXOrO.setBounds(370, 420, 310, 40);

        cmbDifficulty.setBackground(new java.awt.Color(0, 102, 255));
        cmbDifficulty.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        cmbDifficulty.setForeground(new java.awt.Color(255, 255, 255));
        cmbDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium" }));
        getContentPane().add(cmbDifficulty);
        cmbDifficulty.setBounds(370, 340, 310, 40);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_assets/computer-select-background.png"))); // NOI18N
        lblBackground.setText("jLabel1");
        lblBackground.setMaximumSize(new java.awt.Dimension(940, 788));
        lblBackground.setMinimumSize(new java.awt.Dimension(940, 788));
        lblBackground.setName(""); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(940, 788));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-2, -10, 940, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoToGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToGameActionPerformed
        // TODO add your handling code here:
        String difficulty = "";
        String playerLetter = "";
        String computerLetter = "";
                
        switch (cmbDifficulty.getSelectedIndex()) {
            case 0:
                difficulty = "Easy";
                break;
            case 1:
                difficulty = "Medium";
                break;
        }
        
        switch (cmbXOrO.getSelectedIndex()) {
            case 0:
                playerLetter = "X";
                computerLetter = "O";
                break;
            case 1:
                playerLetter = "O";
                computerLetter = "X";
                break;
        }
        
        UltimateTicTacToeAIFrame frmUltimateTicTacToeAI = new UltimateTicTacToeAIFrame();
        frmUltimateTicTacToeAI.setGameProperties(difficulty, computerLetter, playerLetter);
        frmUltimateTicTacToeAI.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnGoToGameActionPerformed
    
    String error;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UltimateComputerSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UltimateComputerSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UltimateComputerSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UltimateComputerSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserDatabase.loadDatabase();
                new UltimateComputerSelectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToGame;
    private javax.swing.JComboBox<String> cmbDifficulty;
    private javax.swing.JComboBox<String> cmbXOrO;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
