/*
 * Group Name: Ludus 
 * Members: Adityya Kaushal, Alexander Tan, Eksjot Multani, Owen Yang
 * ICS4UE
 * August 20-22, 2023
 * Mr. Diakoloukas
 * Purpose: to create a leaderboard page
 * 
 */
package menu;

// Imports LoginFrame, ArrayList, a few classes from the user package and javax table
import authentication_frames.LoginFrame;
import java.util.ArrayList;
import user.User;
import user.UserDatabase;
import javax.swing.table.*;
import user.CurrentUser;

public class LeaderboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public LeaderboardFrame() {
        // Displays the JFrame at the center position of the screen
        setSize(938, 788);
        setLocationRelativeTo(null); // this method display the JFrame to center position of a screen
        initComponents();
        
        // Load Users
        UserDatabase.loadDatabase();
        
        // Call the display top users method
        displayTopUsers();
    }
    
    public void displayTopUsers() {
        
        // Initializes the ArrayList of top players and the number of players to display
        ArrayList <User> topPlayers = UserDatabase.getTopPlayers();
        final int PLAYERS_TO_DISPLAY = 10;
        
        // two columns for username and rating
        String userResult = "";
        String ratingResult = "";
        
        // [username,rating]
        String [] data = new String[3];
        System.out.println("Top Players:");
        System.out.println(topPlayers);
        
        // new model for the leaderbaord table
        DefaultTableModel model = (DefaultTableModel) tblLeaderboard.getModel();
        
        // display either smaller of the size of the top players arraylist or the PLAYERS_TO_DISPLAY
        // loop trough each element up until the numbre of playuers to display
        for (int i = 0;i < Math.min(PLAYERS_TO_DISPLAY, topPlayers.size()); i ++) {
            String username = topPlayers.get(i).getUsername();
            String rating = Long.toString(Math.round(topPlayers.get(i).getRating()));
            String rank = Integer.toString(i + 1);
            System.out.println(username);
            System.out.println(rating);
            model.addRow(new Object[]{rank,username, rating});
        }
        
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnGoToMain = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeaderboard = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(938, 788));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LEADERBOARD");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(0, 150, 940, 50);

        btnGoToMain.setBackground(new java.awt.Color(0, 102, 255));
        btnGoToMain.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnGoToMain.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToMain.setText("Go To Main Menu");
        btnGoToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoToMain);
        btnGoToMain.setBounds(590, 600, 250, 40);

        tblLeaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Username", "Rating"
            }
        ));
        jScrollPane1.setViewportView(tblLeaderboard);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 230, 740, 350);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_assets/leaderboard-background.png"))); // NOI18N
        lblBackground.setText("jLabel1");
        lblBackground.setMaximumSize(new java.awt.Dimension(940, 788));
        lblBackground.setMinimumSize(new java.awt.Dimension(940, 788));
        lblBackground.setName(""); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(940, 850));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 940, 788);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToMainActionPerformed
         // Displays the main menu
        MainMenuFrame frmMainMenu = new MainMenuFrame(); 
        frmMainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGoToMainActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Displays the login page if the current user is null when the window is opened
        if(CurrentUser.getUser() == null) {
            LoginFrame frmLogin = new LoginFrame();
            frmLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblLeaderboard;
    // End of variables declaration//GEN-END:variables
}
