/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package authentication_frames;

import javax.swing.JFrame;

/**
 *
 * @author gaudium
 */
import user.*;

public class frmRegistration extends javax.swing.JFrame {
 
    /**
     * Creates new form frmLogin
     */
    public frmRegistration() {
        UserDatabase.loadDatabase();
        setSize(940, 788);
        setLocationRelativeTo(null); // this method display the JFrame to center position of a screen
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblConfirmPassword = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(940, 788));
        setMinimumSize(new java.awt.Dimension(940, 788));
        setPreferredSize(new java.awt.Dimension(940, 788));
        getContentPane().setLayout(null);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(260, 280, 430, 50);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(260, 170, 430, 50);

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(260, 240, 150, 33);

        lblUsername.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");
        getContentPane().add(lblUsername);
        lblUsername.setBounds(260, 130, 150, 33);

        lblTitle.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Register a new account");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(0, 50, 940, 50);

        btnRegister.setBackground(new java.awt.Color(0, 102, 255));
        btnRegister.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register new account");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(250, 600, 430, 40);

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(260, 350, 150, 33);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(260, 390, 430, 50);

        lblConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setText("Confirm Password:");
        getContentPane().add(lblConfirmPassword);
        lblConfirmPassword.setBounds(260, 460, 250, 33);
        getContentPane().add(txtConfirmPassword);
        txtConfirmPassword.setBounds(260, 500, 430, 50);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_assets/registration-background.png"))); // NOI18N
        lblBackground.setText("jLabel2");
        lblBackground.setMaximumSize(new java.awt.Dimension(940, 788));
        lblBackground.setMinimumSize(new java.awt.Dimension(940, 788));
        lblBackground.setPreferredSize(new java.awt.Dimension(940, 788));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 940, 788);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String error;
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        error = "";
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();
        String email = txtEmail.getText();
        
        String userValidation = Validation.validateUserName(username);
        String emailValidation = Validation.validateEmail(email);
        // ensure username is OK.
        if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || email.isEmpty()) {
            error = "Some fields are empty";
        } else if (!password.equals(confirmPassword)) {
            error = "Passwords and confirmation password don't match";
        } else if (!userValidation.equals("ok")) {
            error = userValidation;
        } else if (!emailValidation.equals("ok")){
            error = emailValidation;
        }
        else if (UserDatabase.existsUser(username) == true) {
            error = "Username already exists";
        }
        else {
            User currentUser = UserDatabase.addUser(username, password, email);
            System.out.println(currentUser.toString());
            // open game jframe
        }
        //lblErrors.setText(error);        

// TODO add your handling code here:
        // Switching window code
        /*
        frmLogin loginFrame = new frmLogin();
        loginFrame.setVisible(true);
        this.dispose();
        */
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
